/* Generated by           cobc 3.2.0 */
/* Generated from         distinct-sources/cbl/subsubsample.cbl */
/* Generated at           Nov 27 2025 11:03:15 */
/* GnuCOBOL build date    Sep 23 2025 17:57:37 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -save-temps=distinct-sources/c distinct-sources/cbl/subsubsample.cbl */

/* Program local variables for 'subsubsample' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[23] __attribute__((aligned));	/* WS-GROUP */

/* End of local data storage */


/* Fields (local) */
static cob_field f_22	= {5, b_17 + 18, &a_1};	/* WS-GROUP-ALPHANUMERIC */

/* End of fields */

