/* Generated by           cobc 3.2.0 */
/* Generated from         distinct-sources/cbl/subsubsample.cbl */
/* Generated at           Nov 27 2025 11:03:15 */
/* GnuCOBOL build date    Sep 23 2025 17:57:37 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -save-temps=distinct-sources/c distinct-sources/cbl/subsubsample.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};


#define cob_nop	if (!module) cob_nop

