/* Generated by           cobc 3.2.0 */
/* Generated from         globals.cbl */
/* Generated at           Dec 09 2025 15:02:41 */
/* GnuCOBOL build date    Sep 23 2025 17:57:37 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g globals.cbl */

/* Program local variables for 'globals' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call pointers */
static cob_call_union	call_globals2;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_21[3] __attribute__((aligned));	/* BAZ */
static cob_u8_t	b_24[3] __attribute__((aligned));	/* FXX */

/* End of local data storage */


/* Fields (local) */
static cob_field f_22	= {1, b_21, &a_4};	/* BAZ-1 */
static cob_field f_23	= {2, b_21 + 1, &a_2};	/* BAZ-2 */
static cob_field f_24	= {3, b_24, &a_1};	/* FXX */

/* End of fields */

