/* Generated by           cobc 3.2.0 */
/* Generated from         globals.cbl */
/* Generated at           Dec 09 2025 15:02:41 */
/* GnuCOBOL build date    Sep 23 2025 17:57:37 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g globals.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"globals.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Dec 09 2025 15:02:41"
#define  COB_MODULE_DATE		20251209
#define  COB_MODULE_TIME		150241

/* Global variables */
#include "globals.c.h"

/* Function prototypes */

static int		globals ();
static int		globals_ (const int);
static void		globals_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (globals ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'globals' */

/* ENTRY 'globals' */

static int
globals ()
{
  return globals_ (0);
}

static int
globals_ (const int entry)
{
  /* Program local variables */
  #include "globals.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 14        : Entry     globals                 : globals.cbl */
  l_2:;
#line 14 "globals.cbl"
  ENTRY_GLOBALS:	cob_nop ();
#line 105 "globals.c"

  /* Line: 14        : MOVE               : globals.cbl */
#line 14 "globals.cbl"
  cob_nop ();
#line 110 "globals.c"
  *(b_18) = 51;

  /* Line: 15        : DISPLAY            : globals.cbl */
#line 15 "globals.cbl"
  cob_nop ();
#line 116 "globals.c"
  cob_display (0, 1, 1, &f_17);

  /* Line: 16        : DISPLAY            : globals.cbl */
#line 16 "globals.cbl"
  cob_nop ();
#line 122 "globals.c"
  cob_display (0, 1, 1, &f_23);

  /* Line: 17        : DISPLAY            : globals.cbl */
#line 17 "globals.cbl"
  cob_nop ();
#line 128 "globals.c"
  cob_display (0, 1, 1, &f_19);

  /* Line: 18        : DISPLAY            : globals.cbl */
#line 18 "globals.cbl"
  cob_nop ();
#line 134 "globals.c"
  cob_display (0, 1, 1, &f_20);

  /* Line: 19        : DISPLAY            : globals.cbl */
#line 19 "globals.cbl"
  cob_nop ();
#line 140 "globals.c"
  cob_display (0, 1, 1, &f_22);

  /* Line: 20        : DISPLAY            : globals.cbl */
#line 20 "globals.cbl"
  cob_nop ();
#line 146 "globals.c"
  cob_display (0, 1, 1, &f_24);

  /* Line: 21        : CALL               : globals.cbl */
#line 21 "globals.cbl"
  cob_nop ();
#line 152 "globals.c"
  cob_glob_ptr->cob_call_params = 0;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_globals2.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_globals2.funcvoid = cob_resolve_cobol ("globals2", 0, 1);
  }
  b_2 = ((int (*)(void))call_globals2.funcint) ();

  /* Line: 22        : GOBACK             : globals.cbl */
#line 22 "globals.cbl"
  cob_nop ();
#line 165 "globals.c"
  goto exit_program;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  globals_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field FOO */
#line 5 "globals.cbl"
  cob_nop ();
#line 218 "globals.c"
  memset (b_17, (unsigned char)'0', 3);

  /* initialize field BAR-1 */
#line 7 "globals.cbl"
  cob_nop ();
#line 224 "globals.c"
  *(cob_u8_ptr)(b_18) = (unsigned char)'0';
  /* initialize field BAR-2 */
#line 8 "globals.cbl"
  cob_nop ();
#line 229 "globals.c"
  memset (b_18 + 1, (unsigned char)' ', 3);

  /* initialize field BAZ-1 */
#line 10 "globals.cbl"
  cob_nop ();
#line 235 "globals.c"
  *(cob_u8_ptr)(b_21) = (unsigned char)' ';
  /* initialize field BAZ-2 */
#line 11 "globals.cbl"
  cob_nop ();
#line 240 "globals.c"
  memset (b_21 + 1, 0x0, 2);

  /* initialize field FXX */
#line 12 "globals.cbl"
  cob_nop ();
#line 246 "globals.c"
  memset (b_24, (unsigned char)'0', 3);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'globals' */

/* Initialize module structure for globals */
static void globals_module_init (cob_module *module)
{
  module->module_name = "globals";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())globals;
  module->module_cancel.funcptr = (void *(*)())globals_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

