/* Generated by           cobc 3.2.0 */
/* Generated from         globals.cbl */
/* Generated at           Dec 05 2025 17:32:48 */
/* GnuCOBOL build date    Sep 23 2025 17:57:37 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g globals.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Data storage */

/* PROGRAM-ID : globals */
static cob_u8_t	b_17[3] __attribute__((aligned));	/* FOO */
static cob_u8_t	b_18[4] __attribute__((aligned));	/* BAR */

/* End of data storage */


/* Attributes */

static const cob_field_attr a_1 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x10,   1,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x11,   4,   0, 0x0041, NULL};


/* Fields */

/* PROGRAM-ID : globals */
static cob_field f_17	= {3, b_17, &a_1};	/* FOO */
static cob_field f_19	= {1, b_18, &a_2};	/* BAR-1 */
static cob_field f_20	= {3, b_18 + 1, &a_3};	/* BAR-2 */

/* End of fields */


#define cob_nop	if (!module) cob_nop

