/* Generated by           cobc 3.2.0 */
/* Generated from         globals2.cbl */
/* Generated at           Dec 09 2025 15:02:39 */
/* GnuCOBOL build date    Sep 23 2025 17:57:37 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -m -g globals2.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Data storage */

/* PROGRAM-ID : globals2 */
static cob_u8_t	b_17[3] __attribute__((aligned));	/* FOO */

/* End of data storage */


/* Attributes */

static const cob_field_attr a_1 =	{0x10,   3,   0, 0x0000, NULL};


/* Fields */

/* PROGRAM-ID : globals2 */
static cob_field f_17	= {3, b_17, &a_1};	/* FOO */

/* End of fields */


#define cob_nop	if (!module) cob_nop

