import readline from "n-readlines";
import * as path from "path";
import * as fs from "fs";
import {DebuggerVariable, Attribute, VariableType} from "./debugger";

function normalizeExistingFileName(f: string): string {
    if (f != undefined && process.platform === "win32") {
        const lc = f.toLowerCase();
        const uc = f.toUpperCase();
        return (!fs.existsSync(lc) || !fs.existsSync(uc)) ? f : lc;
    }
    return f;
}

function cFile (filename: string) : string {
    return path.basename(filename.split('.').slice(0, -1).join('.') + '.c');
}

const procedureRegex = /\/\*\sLine:\s([0-9]+)(\s+:\sEntry\s)?/i;
const procedureFixRegex = /#line\s([0-9]+)\s".*\.c"/i;
const attributeRegex = /static\sconst\scob_field_attr\s(a_[0-9]+).*\{(0x\d+),\s*([0-9-]*),\s*([0-9-]*),\s*(0x\d{4}),.*/i;
const dataStorageRegex = /static\s+(.*)\s+(b_[0-9]+)(\;|\[\d+\]).*\/\*\s+([0-9a-z_\- ]+)\s+\*\//i;
const fieldRegex = /static\s+cob_field\s+([0-9a-z_]+)\s+\=\s+\{(\d+)\,\s+([0-9a-z_]+).+\&(a_\d+).*\/\*\s+([0-9a-z_\-]+)\s+\*\//i;
const fileIncludeRegex = /#include\s+\"([0-9a-z_\-\.\s]+)\"/i;
const fileCobolRegex = /\/\*\sGenerated from\s+([0-9a-z_\-\/\.\s\\:]+)\s+\*\//i;
const functionRegex = /\/\*\sProgram\slocal\svariables\sfor\s'(.*)'\s\*\//i;
const versionRegex = /\/\*\sGenerated by\s+cobc\s([0-9a-z\-\.]+)\s+\*\//i;
const subroutineRegex = /\sPerform\s/i;
const frame_ptrFindRegex = /frame\_ptr\-\-\;/;
const fixOlderFormat = /cob\_trace\_stmt/;

globalThis.varOccurs = [];

function cobEncodeInvalidChars (s: string): string {
    // TODO: properly mimick `libcob:cob_encode_invalid_chars`
    // Meaning: Also replace any character in /[^a-zA-Z0-9-]/ into "_XX", where
    // XX is the hexadecimal ascii code of the characher being replaced
    return s.replace("-","__");
}

export class Line {
    endPerformLine: number;   // 002 - stepOver in routines with "perform"

    public constructor
        (public fileCobol: string,
         public lineCobol: number,
         public fileC: string,
         public rootFileC: string,
         public lineC: number,
         public functionName: string) {
        this.endPerformLine = -1;          // 002 - stepOver in routines with "perform"
    }

    public toString(): string {
        return `${this.fileCobol}:${this.lineCobol} > ${this.fileC}:${this.lineC} | (${this.functionName})`;
    }
}

const dummyLine = new Line('', 0, '', '', 0, '');

export class SourceMap {
    private cwd: string;
    public sourceDirs: string[] = [];
    private lines: Line[] = new Array<Line>();
    private variablesByCobol = new Map<string, DebuggerVariable>();
    private variablesByC = new Map<string, DebuggerVariable>();
    private attributes = new Map<string, Attribute>();
    private dataStorages = new Map<string, DebuggerVariable>();
    private loadedLibs = new Set<string>();
    private version: string;
    private performLine: number = -1; // 002 - stepOver in routines with "perform"
    private isVersion2_2_or_3_1_1: boolean = false;

    constructor(cwd: string, filesCobol: string[], sourceDirs: string[], private log: Function = (_ => {})) {
        this.cwd = fs.realpathSync(path.resolve(cwd));
        this.log(`Source dirs: ${sourceDirs}`);
        for (const cSourceDir of sourceDirs) {
            this.log(`Trying to resolve ${cSourceDir}`);
            let resolved_path = path.resolve(this.cwd, cSourceDir);
            this.log(`Checking for ${resolved_path}`);
            if (fs.existsSync(resolved_path)) {
                this.sourceDirs.push(normalizeExistingFileName(fs.realpathSync(resolved_path)));
            }
        }

        this.sourceDirs.push(this.cwd);

        filesCobol.forEach(e => {
            let c_file = this.lookupSourceFile (cFile (e));
            if (c_file) {
                this.register (c_file);
            }
        });

        this.log(`Resolved source dirs: ${this.sourceDirs}`);
    }

    private lookupSourceFile (file: string) : string | undefined {
        for (const dir of this.sourceDirs) {
            const filePath = path.join (dir, file);
            if (fs.existsSync (filePath)) {
                return normalizeExistingFileName (filePath);
            }
        }
        return;
    }

    public addLib (libFile: string) : boolean {
        if (this.loadedLibs.has (libFile)) {
            return false;
        }
        this.loadedLibs.add (libFile);
        // this.log(`Loading ${libFile}`);
        const c = this.lookupSourceFile (cFile (libFile));
        if (c) {
            this.register (c);
            return true;
        }
        return false;
    }

    public remLib (libFile: string) : boolean {
        if (!this.loadedLibs.has (libFile)) {
            return false;
        }
        this.loadedLibs.delete (libFile);
        // this.log(`Unloading ${libFile}`);
        // Note: assumes there was no FS changes in the meantime.
        // Cleaner way would be to record a mapping between libs and source files.
        const c = this.lookupSourceFile (cFile (libFile));
        if (c) {
            this.unregister (c);
            return true;
        }
        return false;
    }

    private unregister (givenFileC: string) : void {
        const [fileC, cleanedFile] = this.ensureAbsolute (givenFileC);
        this.lines = this.lines.filter (line => line.rootFileC != fileC) ?? [];
        for (const [k, v] of this.variablesByC) {
            if (v.rootFileC == fileC) this.variablesByC.delete(k);
        }
        for (const [k, v] of this.variablesByCobol) {
            if (v.rootFileC == fileC) this.variablesByCobol.delete(k);
        }
    }

    private ensureAbsolute (fileC: string) : [string, string] {
        let nat = fileC;
        if (!path.isAbsolute(fileC)) {
            fileC = path.resolve(this.cwd, fileC);
        }

        const basename = path.basename(fileC);
        const cleanedFile = basename.substring(0, basename.lastIndexOf(".c"));

        return [normalizeExistingFileName(fileC), cleanedFile];
    }

    private register (givenFileC: string) : void {
        // this.log(`Parsing ${givenFileC}`);
        void this.parse (givenFileC); // just parse the file.
    }

    private parse (givenFileC: string,
                     prevLine: string | undefined = undefined,
                    rootFileC: string | undefined = undefined,
                 functionName: string | undefined = undefined) : string {

        const [fileC, cleanedFile] = this.ensureAbsolute (givenFileC);
        rootFileC = rootFileC ?? fileC;

        let lineNumber = 0;
        let row: false | Buffer;
        let fileCobol: string;

        const reader = new readline(fileC);
        while (row = reader.next()) {
            const line = row.toString();
            let match = fileCobolRegex.exec(line);
            if (match) {
                const filename = match[1];
                const filebase = path.basename (filename);
                if (!path.isAbsolute(filename)) {
                    fileCobol = path.resolve(path.dirname (fileC), filename);
                    if (!fs.existsSync(fileCobol)) {
                        fileCobol = path.resolve(path.dirname (fileC), filebase);
                    }
                    if (!fs.existsSync(fileCobol)) {
                        fileCobol = this.lookupSourceFile (filename);
                    }
                } else {
                    fileCobol = filename;
                }
                if (!fs.existsSync(fileCobol)) {
                    fileCobol = this.lookupSourceFile (filebase);
                }
                fileCobol = normalizeExistingFileName (fileCobol);
            }
            match = functionRegex.exec(line);
            if (match) {
                functionName = cobEncodeInvalidChars(match[1]).toLowerCase() + "_";
            }
            match = procedureRegex.exec(line);
            if (match && !match[2]) {
                if (this.lines.length > 0 && this.lines[this.lines.length - 1].fileCobol === fileCobol && this.lines[this.lines.length - 1].lineCobol === parseInt(match[1])) {
                    this.lines.pop();
                }
                if(subroutineRegex.exec(line))
                    this.performLine=-2; // must find line of frame_ptr
                else
                    this.performLine=-1;
                this.lines.push(new Line(fileCobol, parseInt(match[1]), fileC, rootFileC, lineNumber + 2, functionName));
            }
            // fix new codegen
            match = procedureFixRegex.exec(line);
            if (match && this.lines.length > 0 && this.lines[this.lines.length - 1].functionName == functionName) {
                let isOldFormat = fixOlderFormat.exec(prevLine);
                if(this.lines[this.lines.length - 1].fileCobol === fileCobol && (this.isVersion2_2_or_3_1_1 || !isOldFormat)){ // Is it in the old format?
                    let line = this.lines.pop();
                    // this.log (`Fixing line: ${line.toString ()}`);
                    line.lineC = parseInt(match[1]);
                    // this.log (`New    line: ${line.toString ()}`);
                    this.lines.push(line);
                }
            }
            match = attributeRegex.exec(line);
            if (match) {
                const attribute = new Attribute(match[1], VariableType[match[2]], parseInt(match[3]), parseInt(match[4]), match[5]);
                this.attributes.set(`${cleanedFile}.${match[1]}`, attribute);
            }
            match = dataStorageRegex.exec(line);
            if (match) {
                let size: number = null;
                if (match[3].startsWith("[")) {
                    size = parseInt(match[3].substring(1, match[3].length - 1));
                }
                const dataStorage = new DebuggerVariable(match[4], match[2], functionName, rootFileC,
                     new Attribute(null, VariableType[match[1]], 0, 0), size);
                this.dataStorages.set(`${functionName}.${dataStorage.cName}`, dataStorage);
                this.variablesByC.set(`${functionName}.${dataStorage.cName}`, dataStorage);
                this.variablesByCobol.set(`${functionName}.${dataStorage.cobolName.toUpperCase()}`, dataStorage);
            }
            match = fieldRegex.exec(line);
            if (match) {
                const attribute = this.attributes.get(`${cleanedFile}.${match[4]}`);
                const dataStorage = this.dataStorages.get(`${functionName}.${match[3]}`);
                const field = new DebuggerVariable(match[5], match[1], functionName, rootFileC,
                    attribute, parseInt(match[2]));

                this.variablesByC.set(`${functionName}.${field.cName}`, field);

                if (dataStorage) {
                    dataStorage.addChild(field);
                    this.variablesByCobol.set(`${functionName}.${dataStorage.cobolName.toUpperCase()}.${field.cobolName.toUpperCase()}`, field);
                } else {
                    this.variablesByCobol.set(`${functionName}.${field.cobolName.toUpperCase()}`, field);
                }
            }
            match = fileIncludeRegex.exec(line);
            if (match) {
                // Note: we assume the included file is in the same dir as the current file.
                const filename = path.resolve (path.dirname (rootFileC), match[1]);
                functionName = this.parse(filename, prevLine, rootFileC, functionName);
            }
            match = versionRegex.exec(line);
            if (match) {
                this.version = match[1];
                if(this.version.startsWith("2.2") || this.version.startsWith("3.1.1")) this.isVersion2_2_or_3_1_1 = true;
            }
            if(this.performLine == -2){
                match = frame_ptrFindRegex.exec(line);
                if(match){
                    let line = this.lines.pop();
                    line.endPerformLine = lineNumber+1;
                    this.lines.push(line);
                }
            }
            lineNumber++;
            prevLine = line;
        }

        return functionName;
    }

    public getVariablesByC(): IterableIterator<DebuggerVariable> {
        return this.variablesByC.values();
    }

    public getVariablesByCobol(): IterableIterator<DebuggerVariable> {
        return this.variablesByCobol.values();
    }

    public getLinesCount(): number {
        return this.lines.length;
    }

    public getVariablesCount(): number {
        return this.variablesByC.size;
    }

    public getVariableByC(varC: string): DebuggerVariable {
        if (this.variablesByC.has(varC)) {
            return this.variablesByC.get(varC);
        }
        return null;
    }

    public findVariableByCobol(functionName: string, name: string): DebuggerVariable {
        for (const key of this.variablesByCobol.keys()) {
            if (key.startsWith(functionName) && key.endsWith(`.${name.toUpperCase()}`)) {
                return this.variablesByCobol.get(key);
            }
        }
        return null;
    }

    public getVariableByCobol(path: string): DebuggerVariable {
        return this.variablesByCobol.get(path);
    }

    public hasLineCobol(fileC: string, lineC: number): boolean {
        if(!fileC || !lineC) return false;
        if (!path.isAbsolute(fileC)) {
            fileC = path.join(this.cwd, fileC);
        }
        return this.lines.some(e => e.fileC === fileC && e.lineC === lineC);
    }

    // 002 - stepOver in routines with "perform"
    public hasLineSubroutine(fileC: string, lineC: number): number {
        if(!fileC || !lineC) return -1;
        if (!path.isAbsolute(fileC)) {
            fileC = path.join(this.cwd, fileC);
        }
        return this.lines.find(e => e.fileC === fileC && e.lineC === lineC)?.endPerformLine ?? -1;
    }
    // 002

    public hasLineC(fileCobol: string, lineCobol: number): boolean {
        if (!path.isAbsolute(fileCobol)) {
            fileCobol = path.join(this.cwd, fileCobol);
        }
        return this.lines.some(e => e.fileCobol === fileCobol && e.lineCobol === lineCobol);
    }

    public getLineC(fileCobol: string, lineCobol: number): Line {
        if (!path.isAbsolute(fileCobol)) {
            fileCobol = path.join(this.cwd, fileCobol);
        }
        return this.lines.find(e => e.fileCobol === fileCobol && e.lineCobol === lineCobol) ?? dummyLine;
    }

    public getLineCobol(fileC: string, lineC: number): Line {
        if (!fileC) {
            return dummyLine;
        }
        if (!path.isAbsolute(fileC)) {
            fileC = path.join(this.cwd, fileC);
        }
        return this.lines.find(e => e.fileC === fileC && e.lineC === lineC) ?? dummyLine;
    }

    public getVersion(): string {
        return this.version;
    }

    public toString(event = "created"): string {
        let out = `SourceMap ${event}: lines ${this.lines.length}, vars ${this.variablesByC.size}\n`;

        this.lines.forEach(e => {
            out += e.toString() + "\n";
        });

        this.variablesByC.forEach((value, key) => {
            out += `${key}[${value.attribute?.cName}] > ${value.cobolName}\n`;
        });

        this.variablesByCobol.forEach((value, key) => {
            out += `${key}[${value.attribute?.cName}] > ${value.cName}\n`;
        });

        return out;
    }

}
